package com.example.resqtap.chat;

import com.example.resqtap.R;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 * Katalog rasmi isyarat bahasa isyarat BIM SignBank.
 * Mengandungi kesemua lukisan lakaran hitam putih rasmi tanpa watermark
 * yang disepadukan secara langsung dengan sistem Sign Camera viewfinder,
 * transkripsi ayat masa-nyata, dan paparan panduan.
 */
public final class BimSignCatalog {
    private static List<BimSignItem> cachedList;

    private BimSignCatalog() {}

    public static synchronized List<BimSignItem> getSigns() {
        if (cachedList != null) {
            return cachedList;
        }
        List<BimSignItem> list = new ArrayList<>(465);
        list.add(new BimSignItem(140, "Pecat, Dibuang kerja", "Sack, Fired", R.drawable.img_bim_pecat_dibuang_kerja, "https://youtu.be/qa1M2WQuEtk", "", ""));
        list.add(new BimSignItem(144, "Pencen", "Pension", R.drawable.img_bim_pencen, "https://youtu.be/LO_BdsB-EHM", "", ""));
        list.add(new BimSignItem(148, "Sah", "Confirm", R.drawable.img_bim_sah, "https://youtu.be/w0yDZiSo2Lw", "", ""));
        list.add(new BimSignItem(156, "Bahasa Malaysia", "Malaysian language", R.drawable.img_bim_bahasa_malaysia, "https://youtu.be/gles_Or0nAI", "", ""));
        list.add(new BimSignItem(160, "Bidang, Jurusan", "Field (of study), Major (of study)", R.drawable.img_bim_bidang_jurusan, "https://youtu.be/SWvidPMgW8E", "", ""));
        list.add(new BimSignItem(164, "Diploma", "Diploma", R.drawable.img_bim_diploma, "https://youtu.be/Wda3p-3uHh4", "", ""));
        list.add(new BimSignItem(172, "Kamus", "Dictionary", R.drawable.img_bim_kamus, "https://youtu.be/a_ZzoLrKgbs", "", ""));
        list.add(new BimSignItem(184, "Pelajaran", "Lesson", R.drawable.img_bim_pelajaran, "https://youtu.be/3q8zXdRg7gA", "", ""));
        list.add(new BimSignItem(196, "Ujian", "Test", R.drawable.img_bim_ujian, "https://youtu.be/wZluWjUMlDA", "", ""));
        list.add(new BimSignItem(212, "Busuk hati", "Bad hearted", R.drawable.img_bim_busuk_hati, "https://youtu.be/QhxyR9i82EE", "", ""));
        list.add(new BimSignItem(1246, "Helikopter", "Helicopter", R.drawable.img_bim_helikopter, "https://youtu.be/4lDn3CXZx5I", "", ""));
        list.add(new BimSignItem(1250, "Kapal layar, Lanchang", "Yacht, Sailboat", R.drawable.img_bim_kapal_layar_lanchang, "https://youtu.be/OmK2M9RF6VY", "", ""));
        list.add(new BimSignItem(1254, "Kereta", "Car", R.drawable.img_bim_kereta, "https://youtu.be/NivM4IsyRfY", "", ""));
        list.add(new BimSignItem(1258, "Lori", "Lorry", R.drawable.img_bim_lori, "https://youtu.be/HH5o9_v6LP0", "", ""));
        list.add(new BimSignItem(1262, "Motosikal", "Motorcycle", R.drawable.img_bim_motosikal, "https://youtu.be/x83CNoer06w", "", ""));
        list.add(new BimSignItem(1266, "Roket", "Rocket", R.drawable.img_bim_roket, "https://youtu.be/nJYiZrWgue4", "", ""));
        list.add(new BimSignItem(134, "Bersara", "Retired", R.drawable.img_bim_bersara, "https://youtu.be/U3VLfYXqabk", "", ""));
        list.add(new BimSignItem(138, "Letak Jawatan", "Resign", R.drawable.img_bim_letak_jawatan, "https://youtu.be/un4npvkwT_M", "", ""));
        list.add(new BimSignItem(142, "Pekerjaan", "Occupation, Job", R.drawable.img_bim_pekerjaan, "https://youtu.be/O5QQ787mxio", "", ""));
        list.add(new BimSignItem(146, "Profesional", "Professional", R.drawable.img_bim_profesional, "https://youtu.be/jfiAOPyuS0M", "", ""));
        list.add(new BimSignItem(150, "Sementara", "Temporary", R.drawable.img_bim_sementara, "https://youtu.be/CRRn1bWs_ds", "", ""));
        list.add(new BimSignItem(136, "Bonus", "Bonus", R.drawable.img_bim_bonus, "https://youtu.be/NUq8qhKXKqk", "", ""));
        list.add(new BimSignItem(168, "Geografi", "Geography", R.drawable.img_bim_geografi, "https://youtu.be/4dn60ODmhLE", "", ""));
        list.add(new BimSignItem(176, "Kursus", "Courses", R.drawable.img_bim_kursus, "https://youtu.be/FewiU2M_ceg", "", ""));
        list.add(new BimSignItem(180, "Ajar, Mengajar", "Teach, Teaching", R.drawable.img_bim_ajar_mengajar, "https://youtu.be/HuzxUwfeDhU", "", ""));
        list.add(new BimSignItem(188, "Peperiksaan", "Examination", R.drawable.img_bim_peperiksaan, "https://youtu.be/u97LPRTotco", "", ""));
        list.add(new BimSignItem(192, "Sejarah", "History", R.drawable.img_bim_sejarah, "https://youtu.be/Lj5RmaNXURc", "", ""));
        list.add(new BimSignItem(200, "Bangga", "Proud", R.drawable.img_bim_bangga, "https://youtu.be/XkDsD0RVmJQ", "", ""));
        list.add(new BimSignItem(204, "Benci", "Hate", R.drawable.img_bim_benci, "https://youtu.be/tHqLOJTuNaE", "", ""));
        list.add(new BimSignItem(208, "Bimbang (II)", "Anxiety", R.drawable.img_bim_bimbang_ii, "https://youtu.be/mHFLsmEXDko", "", ""));
        list.add(new BimSignItem(1248, "Kapal", "Ship", R.drawable.img_bim_kapal, "https://youtu.be/ByxKhHvezOM", "", ""));
        list.add(new BimSignItem(1252, "Kapal terbang", "Aeroplane, Airplane, Flight", R.drawable.img_bim_kapal_terbang, "https://youtu.be/bBVS9OtwZ5s", "", ""));
        list.add(new BimSignItem(1256, "Keretapi", "Train", R.drawable.img_bim_keretapi, "https://youtu.be/hH_lzKNDdJE", "", ""));
        list.add(new BimSignItem(154, "Bahasa Inggeris", "English language", R.drawable.img_bim_bahasa_inggeris, "https://youtu.be/TXrX9aOcJhE", "", ""));
        list.add(new BimSignItem(158, "Belajar", "Learn", R.drawable.img_bim_belajar, "https://youtu.be/nFWPMtEFiCI", "", ""));
        list.add(new BimSignItem(162, "Biologi", "Biology", R.drawable.img_bim_biologi, "https://youtu.be/Thznq5xzaUM", "", ""));
        list.add(new BimSignItem(166, "Fizik", "Physic", R.drawable.img_bim_fizik, "https://youtu.be/kl6DkEdTp2E", "", ""));
        list.add(new BimSignItem(170, "Grafik", "Graphic", R.drawable.img_bim_grafik, "https://youtu.be/l4z-qB3CgK0", "", ""));
        list.add(new BimSignItem(174, "Kimia", "Chemistry", R.drawable.img_bim_kimia, "https://youtu.be/OivSveYv6nc", "", ""));
        list.add(new BimSignItem(178, "Matematik", "Mathematics", R.drawable.img_bim_matematik, "https://youtu.be/XwlqP8wYe8A", "", ""));
        list.add(new BimSignItem(182, "Muzik", "Music", R.drawable.img_bim_muzik, "https://youtu.be/YoQ0IsA2Vmg", "", ""));
        list.add(new BimSignItem(186, "Pendidikan", "Education", R.drawable.img_bim_pendidikan, "https://youtu.be/HKX3IV0bQ2k", "", ""));
        list.add(new BimSignItem(190, "Sains", "Science", R.drawable.img_bim_sains, "https://youtu.be/vL2rml0od4A", "", ""));
        list.add(new BimSignItem(194, "Sijil", "Certificate", R.drawable.img_bim_sijil, "https://youtu.be/3Evr3RlBN4k", "", ""));
        list.add(new BimSignItem(198, "Baik Hati", "Kind hearted", R.drawable.img_bim_baik_hati, "https://youtu.be/YxRxV_56OT4", "", ""));
        list.add(new BimSignItem(202, "Bebas (tidak diikat, dikurung atau ditahan secara paksa)", "Free (not bound, confined, or detained by force)", R.drawable.img_bim_bebas_tidak_diikat_dikurung_atau_ditahan_secara_paksa, "https://youtu.be/AVO2d5db_2A", "", ""));
        list.add(new BimSignItem(206, "Bimbang (I)", "Worry", R.drawable.img_bim_bimbang_i, "https://youtu.be/khF6tcCS3Jo", "", ""));
        list.add(new BimSignItem(210, "Bosan", "Bored", R.drawable.img_bim_bosan, "https://youtu.be/XjdTCqBDAKE", "", ""));
        list.add(new BimSignItem(214, "Cemburu", "Jealous", R.drawable.img_bim_cemburu, "https://youtu.be/9wjhLA-yTFc", "", ""));
        list.add(new BimSignItem(216, "Cinta", "Love (I)", R.drawable.img_bim_cinta, "https://youtu.be/6-uLC9vG8EA", "", ""));
        list.add(new BimSignItem(218, "Bahagia, Gembira", "Happy", R.drawable.img_bim_bahagia_gembira, "https://youtu.be/hUDdRMnSo7k", "", ""));
        list.add(new BimSignItem(220, "Simpati", "Sympathy", R.drawable.img_bim_simpati, "https://youtu.be/iYnIkTjKxtk", "", ""));
        list.add(new BimSignItem(222, "Kesal", "Regret", R.drawable.img_bim_kesal, "https://youtu.be/gKgRLAd6wLg", "", ""));
        list.add(new BimSignItem(224, "Lega", "Relieved", R.drawable.img_bim_lega, "https://youtu.be/2TofMnvKvT4", "", ""));
        list.add(new BimSignItem(226, "Lucu", "Funny (I)", R.drawable.img_bim_lucu, "https://youtu.be/uP47e6ivvow", "", ""));
        list.add(new BimSignItem(228, "Malu", "Shy", R.drawable.img_bim_malu, "https://youtu.be/A9nr9s6uckE", "", ""));
        list.add(new BimSignItem(230, "Marah", "Angry", R.drawable.img_bim_marah, "https://youtu.be/nbpieyZjaH8", "", ""));
        list.add(new BimSignItem(232, "Mengantuk", "Sleepy", R.drawable.img_bim_mengantuk, "https://youtu.be/nEf1dA4emJk", "", ""));
        list.add(new BimSignItem(234, "Perasaan", "Feeling", R.drawable.img_bim_perasaan, "https://youtu.be/m3IB-m2WbIw", "", ""));
        list.add(new BimSignItem(236, "Puas hati", "Satisfied", R.drawable.img_bim_puas_hati, "https://youtu.be/vzolkzVg1vA", "", ""));
        list.add(new BimSignItem(256, "Terkejut", "Surprised", R.drawable.img_bim_terkejut, "https://youtu.be/S4mIdVuqaPs", "", ""));
        list.add(new BimSignItem(272, "Kebajikan", "Welfare", R.drawable.img_bim_kebajikan, "https://youtu.be/VyrCKpx22pI", "", ""));
        list.add(new BimSignItem(280, "Pekak", "Deaf", R.drawable.img_bim_pekak, "https://youtu.be/rojDkce0svY", "", ""));
        list.add(new BimSignItem(284, "Pencacar koklea", "Cochlear implant", R.drawable.img_bim_pencacar_koklea, "https://youtu.be/wHnRAm-GGec", "", ""));
        list.add(new BimSignItem(288, "Suara", "Voice", R.drawable.img_bim_suara, "https://youtu.be/CsdfTLdUdKY", "", ""));
        list.add(new BimSignItem(292, "Agar-agar", "Jelly", R.drawable.img_bim_agar_agar, "https://youtu.be/A0BDQgMfVeU", "", ""));
        list.add(new BimSignItem(296, "Bihun", "Bee Hoon (Rice Vermicelli, a thin form of noodle)", R.drawable.img_bim_bihun, "https://youtu.be/NU2f8f_psmo", "", ""));
        list.add(new BimSignItem(300, "Bubur", "Porridge", R.drawable.img_bim_bubur, "https://youtu.be/LbAjGVzY1NU", "", ""));
        list.add(new BimSignItem(308, "Goreng", "Fried", R.drawable.img_bim_goreng, "https://youtu.be/V6bMaqHQnRU", "", ""));
        list.add(new BimSignItem(328, "Mentega", "Butter", R.drawable.img_bim_mentega, "https://youtu.be/2juh4WWurWc", "", ""));
        list.add(new BimSignItem(332, "Nasi lemak", "Nasi lemak", R.drawable.img_bim_nasi_lemak, "https://youtu.be/KhvAfNIrEs4", "", ""));
        list.add(new BimSignItem(344, "Roti Naan", "Roti Naan", R.drawable.img_bim_roti_naan, "https://youtu.be/0ShYCyeubFk", "", ""));
        list.add(new BimSignItem(348, "Sate", "Satay", R.drawable.img_bim_sate, "https://youtu.be/Dvd7M9eJ_xY", "", ""));
        list.add(new BimSignItem(356, "Sup", "Soup", R.drawable.img_bim_sup, "https://youtu.be/szxoFtSd7WM", "", ""));
        list.add(new BimSignItem(360, "Coke", "Coke", R.drawable.img_bim_coke, "https://youtu.be/1XCa10GaFmQ", "", ""));
        list.add(new BimSignItem(376, "Manis", "Sweet", R.drawable.img_bim_manis, "https://youtu.be/ezA3SShc7gs", "", ""));
        list.add(new BimSignItem(388, "Februari", "February", R.drawable.img_bim_februari, "https://youtu.be/7R3dHQ2qqPE", "", ""));
        list.add(new BimSignItem(392, "Julai", "July", R.drawable.img_bim_julai, "https://youtu.be/q1-G_gftj4w", "", ""));
        list.add(new BimSignItem(404, "Oktober", "October", R.drawable.img_bim_oktober, "https://youtu.be/JfgB5A7YCKY", "", ""));
        list.add(new BimSignItem(412, "Dahulu (I)", "Past", R.drawable.img_bim_dahulu_i, "https://youtu.be/9kKRwxxtPs8", "", ""));
        list.add(new BimSignItem(416, "Esok", "Tomorrow", R.drawable.img_bim_esok, "https://youtu.be/DDhGVdBnYw0", "", ""));
        list.add(new BimSignItem(420, "Hari ini", "Today", R.drawable.img_bim_hari_ini, "https://youtu.be/wIhKPNIEwjk", "", ""));
        list.add(new BimSignItem(1260, "LRT", "LRT", R.drawable.img_bim_lrt, "https://youtu.be/MUXZpOnxlSs", "", ""));
        list.add(new BimSignItem(238, "Rindu", "Miss (Feeling)", R.drawable.img_bim_rindu, "https://youtu.be/BA2nUYUjniU", "", ""));
        list.add(new BimSignItem(242, "Sabar", "Patient", R.drawable.img_bim_sabar, "https://youtu.be/rlocyAkNYww", "", ""));
        list.add(new BimSignItem(246, "Sedih", "Sad", R.drawable.img_bim_sedih, "https://youtu.be/ZO2dwlCbr2M", "", ""));
        list.add(new BimSignItem(250, "Kasihan", "Pity", R.drawable.img_bim_kasihan, "https://youtu.be/rc_7dyyEqk4", "", ""));
        list.add(new BimSignItem(254, "Tengking", "Scold", R.drawable.img_bim_tengking, "https://youtu.be/UqgGjS2RpSc", "", ""));
        list.add(new BimSignItem(258, "Tidak suka", "Dislike", R.drawable.img_bim_tidak_suka, "https://youtu.be/yxxJPslxLBE", "", ""));
        list.add(new BimSignItem(266, "Cacat", "Disabled", R.drawable.img_bim_cacat, "https://youtu.be/FetFa4OYSiY", "", ""));
        list.add(new BimSignItem(270, "Isyarat", "Sign", R.drawable.img_bim_isyarat, "https://youtu.be/IvRLLlvBdyw", "", ""));
        list.add(new BimSignItem(274, "Kurang pendengaran", "Hard-of-Hearing", R.drawable.img_bim_kurang_pendengaran, "https://youtu.be/ypxAUkXBPA8", "", ""));
        list.add(new BimSignItem(278, "Normal", "Normal", R.drawable.img_bim_normal, "https://youtu.be/mQgk8k6uhvg", "", ""));
        list.add(new BimSignItem(282, "Pemulihan (Rehabilitasi)", "Rehabilitation", R.drawable.img_bim_pemulihan_rehabilitasi, "https://youtu.be/QhPbXyMJ6tw", "", ""));
        list.add(new BimSignItem(286, "Spastik", "Spastic", R.drawable.img_bim_spastik, "https://youtu.be/u_fkdCjtMc0", "", ""));
        list.add(new BimSignItem(290, "Jurubahasa Isyarat", "Sign Language Interpreter", R.drawable.img_bim_jurubahasa_isyarat, "https://youtu.be/iklx7eWnC_o", "", ""));
        list.add(new BimSignItem(294, "Ais krim", "Ice cream", R.drawable.img_bim_ais_krim, "https://youtu.be/EL-8oxNlM9k", "", ""));
        list.add(new BimSignItem(298, "Biskut", "Biscuit", R.drawable.img_bim_biskut, "https://youtu.be/JDxVb2cV6XE", "", ""));
        list.add(new BimSignItem(302, "Burger", "Burger", R.drawable.img_bim_burger, "https://youtu.be/dKTpIm8pnOQ", "", ""));
        list.add(new BimSignItem(306, "Garam", "Salt", R.drawable.img_bim_garam, "https://youtu.be/FHJEuWTG_k8", "", ""));
        list.add(new BimSignItem(310, "Gula", "Sugar", R.drawable.img_bim_gula, "https://youtu.be/N_jvgpxkMfo", "", ""));
        list.add(new BimSignItem(314, "Keju", "Cheese", R.drawable.img_bim_keju, "https://youtu.be/_dZLcm4S2Ic", "", ""));
        list.add(new BimSignItem(318, "Ketupat", "Ketupat", R.drawable.img_bim_ketupat, "https://youtu.be/eQ6HErpQFw0", "", ""));
        list.add(new BimSignItem(322, "Kuih", "Cake (II)", R.drawable.img_bim_kuih, "https://youtu.be/V342Fm4uH3M", "", ""));
        list.add(new BimSignItem(326, "Mee", "Noodle", R.drawable.img_bim_mee, "https://youtu.be/twmoJCB0gCQ", "", ""));
        list.add(new BimSignItem(330, "Nasi", "Rice", R.drawable.img_bim_nasi, "https://youtu.be/x3MUXiqqXIk", "", ""));
        list.add(new BimSignItem(240, "Risau", "Worried", R.drawable.img_bim_risau, "https://youtu.be/Z1g0rikCiXQ", "", ""));
        list.add(new BimSignItem(244, "Sayang", "Love (II)", R.drawable.img_bim_sayang, "https://youtu.be/QGOfDXVXuWg", "", ""));
        list.add(new BimSignItem(248, "Sendirian, Seorang diri", "Alone", R.drawable.img_bim_sendirian_seorang_diri, "https://youtu.be/j_Sd5dwgJAU", "", ""));
        list.add(new BimSignItem(252, "Suka", "Like", R.drawable.img_bim_suka, "https://youtu.be/NOnXJPkAFvA", "", ""));
        list.add(new BimSignItem(260, "Alat pendengaran", "Hearing aid", R.drawable.img_bim_alat_pendengaran, "https://youtu.be/duaD2-Jy3Kc", "", ""));
        list.add(new BimSignItem(264, "Buta", "Blind", R.drawable.img_bim_buta, "https://youtu.be/8pwFkXtnqaA", "", ""));
        list.add(new BimSignItem(268, "Ejaan jari", "Finger spelling", R.drawable.img_bim_ejaan_jari, "https://youtu.be/3JXUEpYbhu8", "", ""));
        list.add(new BimSignItem(276, "Lisan", "Oral", R.drawable.img_bim_lisan, "https://youtu.be/0iXphux5puk", "", ""));
        list.add(new BimSignItem(304, "Daging", "Meat", R.drawable.img_bim_daging, "https://youtu.be/zYu0bsDJ7B8", "", ""));
        list.add(new BimSignItem(312, "Gula-gula", "Sweets", R.drawable.img_bim_gula_gula, "https://youtu.be/TgfPGPrWtzQ", "", ""));
        list.add(new BimSignItem(316, "Kek", "Cake (I)", R.drawable.img_bim_kek, "https://youtu.be/LSTjElfXYi4", "", ""));
        list.add(new BimSignItem(320, "Kicap", "Soya sauce", R.drawable.img_bim_kicap, "https://youtu.be/t5ek_ZVy_kU", "", ""));
        list.add(new BimSignItem(324, "Lemang", "Lemang", R.drawable.img_bim_lemang, "https://youtu.be/-X2PO-y_BoU", "", ""));
        list.add(new BimSignItem(336, "Rojak", "Rojak", R.drawable.img_bim_rojak, "https://youtu.be/wdYzlE70A5E", "", ""));
        list.add(new BimSignItem(340, "Roti Canai", "Roti Canai", R.drawable.img_bim_roti_canai, "https://youtu.be/83VoefD6Eb4", "", ""));
        list.add(new BimSignItem(364, "Milo", "Milo", R.drawable.img_bim_milo, "https://youtu.be/8gfXpZCSudA", "", ""));
        list.add(new BimSignItem(368, "Sirap", "Syrup", R.drawable.img_bim_sirap, "https://youtu.be/oMbgLC73dLQ", "", ""));
        list.add(new BimSignItem(372, "Teh", "Tea", R.drawable.img_bim_teh, "https://youtu.be/U88u9JzfAZY", "", ""));
        list.add(new BimSignItem(380, "Pahit", "Bitter", R.drawable.img_bim_pahit, "https://youtu.be/AtGLxuUHGjc", "", ""));
        list.add(new BimSignItem(384, "April", "April", R.drawable.img_bim_april, "https://youtu.be/khFS36-8_k8", "", ""));
        list.add(new BimSignItem(396, "Mac", "March", R.drawable.img_bim_mac, "https://youtu.be/Tsn2ipNIc7o", "", ""));
        list.add(new BimSignItem(400, "November", "November", R.drawable.img_bim_november, "https://youtu.be/jjwDEJQE4lU", "", ""));
        list.add(new BimSignItem(408, "Bulan (I)", "Month", R.drawable.img_bim_bulan_i, "https://youtu.be/6wZrAkXN9qE", "", ""));
        list.add(new BimSignItem(1264, "Pengangkutan", "Transportation", R.drawable.img_bim_pengangkutan, "https://youtu.be/K369kuHYzCc", "", ""));
        list.add(new BimSignItem(334, "Pulut", "Glutinous rice", R.drawable.img_bim_pulut, "https://youtu.be/dooDEN9khao", "", ""));
        list.add(new BimSignItem(338, "Roti", "Bread", R.drawable.img_bim_roti, "https://youtu.be/B_1KmBLoYfI", "", ""));
        list.add(new BimSignItem(342, "Roti Jala", "Roti Jala", R.drawable.img_bim_roti_jala, "https://youtu.be/o7fvhk8YW0M", "", ""));
        list.add(new BimSignItem(346, "Santan", "Coconut milk", R.drawable.img_bim_santan, "https://youtu.be/O1cO-7jXQZQ", "", ""));
        list.add(new BimSignItem(350, "Serbuk lada", "Pepper", R.drawable.img_bim_serbuk_lada, "https://youtu.be/bQEYTiss4iQ", "", ""));
        list.add(new BimSignItem(354, "Sosej", "Hot dog", R.drawable.img_bim_sosej, "https://youtu.be/BHcdg3RyviY", "", ""));
        list.add(new BimSignItem(358, "Telur", "Egg", R.drawable.img_bim_telur, "https://youtu.be/sMGEvq9-Twk", "", ""));
        list.add(new BimSignItem(362, "Kopi", "Coffee", R.drawable.img_bim_kopi, "https://youtu.be/wNVOqWMraxQ", "", ""));
        list.add(new BimSignItem(366, "Nescafe", "Nescafe", R.drawable.img_bim_nescafe, "https://youtu.be/WtRD1ZZSJVA", "", ""));
        list.add(new BimSignItem(370, "Susu", "Milk", R.drawable.img_bim_susu, "https://youtu.be/Apl0szdK93g", "", ""));
        list.add(new BimSignItem(374, "Teh Tarik", "Teh Tarik", R.drawable.img_bim_teh_tarik, "https://youtu.be/VxYCY9yihbI", "", ""));
        list.add(new BimSignItem(378, "Masam", "Sour", R.drawable.img_bim_masam, "https://youtu.be/Tsj-KUrsmRg", "", ""));
        list.add(new BimSignItem(382, "Pedas", "Hot, Spicy", R.drawable.img_bim_pedas, "https://youtu.be/acRf4OSGPP4", "", ""));
        list.add(new BimSignItem(386, "Disember", "December", R.drawable.img_bim_disember, "https://youtu.be/lFdnbxf7KtU", "", ""));
        list.add(new BimSignItem(390, "Januari", "January", R.drawable.img_bim_januari, "https://youtu.be/KbcUdvU-O0U", "", ""));
        list.add(new BimSignItem(394, "Jun", "June", R.drawable.img_bim_jun, "https://youtu.be/JtEiDbM8Wm0", "", ""));
        list.add(new BimSignItem(398, "Mei", "May", R.drawable.img_bim_mei, "https://youtu.be/Lw1rXSaMfxo", "", ""));
        list.add(new BimSignItem(402, "Ogos", "August", R.drawable.img_bim_ogos, "https://youtu.be/ZKuDifN_hWI", "", ""));
        list.add(new BimSignItem(406, "September", "September", R.drawable.img_bim_september, "https://youtu.be/h8MoJMM9a8E", "", ""));
        list.add(new BimSignItem(410, "Cuti", "Holiday", R.drawable.img_bim_cuti, "https://youtu.be/GmEZ6qbRLvc", "", ""));
        list.add(new BimSignItem(414, "Dahulu (II)", "Long time ago, some time ago", R.drawable.img_bim_dahulu_ii, "https://youtu.be/xY8cprclsl0", "", ""));
        list.add(new BimSignItem(418, "Hari", "Day", R.drawable.img_bim_hari, "https://youtu.be/QnL-btp-Iwo", "", ""));
        list.add(new BimSignItem(422, "Jam", "Hour", R.drawable.img_bim_jam, "https://youtu.be/LV76qMak38Y", "", ""));
        list.add(new BimSignItem(424, "Kalendar", "Calendar", R.drawable.img_bim_kalendar, "https://youtu.be/yN1_J8p_kKM", "", ""));
        list.add(new BimSignItem(426, "Malam", "Night", R.drawable.img_bim_malam, "https://youtu.be/m1S8Sl9Pdy4", "", ""));
        list.add(new BimSignItem(428, "Minggu", "Week", R.drawable.img_bim_minggu, "https://youtu.be/Bpp-8UOJswE", "", ""));
        list.add(new BimSignItem(452, "Tahun depan", "Next year", R.drawable.img_bim_tahun_depan, "https://youtu.be/xaXXFY1zsSg", "", ""));
        list.add(new BimSignItem(456, "Tahun lalu, Tahun lepas", "Last year", R.drawable.img_bim_tahun_lalu_tahun_lepas, "https://youtu.be/RsM6X6ga0-w", "", ""));
        list.add(new BimSignItem(476, "Selasa", "Tuesday", R.drawable.img_bim_selasa, "https://youtu.be/V6fotXa8NYY", "", ""));
        list.add(new BimSignItem(480, "Bibir", "Lip", R.drawable.img_bim_bibir, "https://youtu.be/NtlAjzloUU4", "", ""));
        list.add(new BimSignItem(484, "Dagu", "Chin", R.drawable.img_bim_dagu, "https://youtu.be/bHuK7kt8MZM", "", ""));
        list.add(new BimSignItem(500, "Leher", "Neck", R.drawable.img_bim_leher, "https://youtu.be/z9BxEVL9BBY", "", ""));
        list.add(new BimSignItem(504, "Mata", "Eye", R.drawable.img_bim_mata, "https://youtu.be/GoiKpfM6PII", "", ""));
        list.add(new BimSignItem(508, "Mulut", "Mouth", R.drawable.img_bim_mulut, "https://youtu.be/3acSTKJorBg", "", ""));
        list.add(new BimSignItem(520, "Cik (panggilan untuk wanita atau perempuan yang belum berkahwin)", "Miss (a title prefixed to the name of an unmarried woman or girl)", R.drawable.img_bim_cik_panggilan_untuk_wanita_atau_perempuan_yang_belum_berkahwin, "https://youtu.be/IJ83QjcaA1Y", "", ""));
        list.add(new BimSignItem(524, "Dato' (gelaran kehormatan yg dianugerahkan oleh Ketua Negara atau Ketua Negeri kpd orang-orang tertentu)", "Dato' (an honorary title conferred by the Head of State on certain persons)", R.drawable.img_bim_dato_gelaran_kehormatan_yg_dianugerahkan_oleh_ketua_negara_atau_ketua_negeri_kpd_orang_orang_tertentu, "https://youtu.be/UoBiKiGgtiU", "", ""));
        list.add(new BimSignItem(528, "Encik (gelaran yg digunakan sebelum nama orang lelaki (yg tidak mempunyai sebarang gelaran spt Dato', Tengku dan sebagainya)", "Mister (a title used before the name of a man (who does not have any title such as Dato', Tengku, and so on))", R.drawable.img_bim_encik_gelaran_yg_digunakan_sebelum_nama_orang_lelaki_yg_tidak_mempunyai_sebarang_gelaran_spt_dato_tengku_dan_sebagainya, "https://youtu.be/isKPQwN5SjI", "", ""));
        list.add(new BimSignItem(532, "Kamu", "Your", R.drawable.img_bim_kamu, "https://youtu.be/zRgFmS9lAB0", "", ""));
        list.add(new BimSignItem(544, "Puteri", "Princess", R.drawable.img_bim_puteri, "https://youtu.be/QeZJ2VMvwYI", "", ""));
        list.add(new BimSignItem(560, "Adik perempuan", "Younger sister", R.drawable.img_bim_adik_perempuan, "https://youtu.be/yOHur9ac1Ds", "", ""));
        list.add(new BimSignItem(568, "Anak perempuan", "Daughter", R.drawable.img_bim_anak_perempuan, "https://youtu.be/tz_NMZxFsqk", "", ""));
        list.add(new BimSignItem(572, "Bapa, Ayah", "Father, Dad", R.drawable.img_bim_bapa_ayah, "https://youtu.be/387R2ObhNFk", "", ""));
        list.add(new BimSignItem(576, "Berdua-duaan", "Dating", R.drawable.img_bim_berdua_duaan, "https://youtu.be/8vQ05Nmi48I", "", ""));
        list.add(new BimSignItem(580, "Bertunang", "Engaged", R.drawable.img_bim_bertunang, "https://youtu.be/9Q_gwzlciqk", "", ""));
        list.add(new BimSignItem(624, "Saudara", "Relative", R.drawable.img_bim_saudara, "https://youtu.be/rFvVkxrnkGU", "", ""));
        list.add(new BimSignItem(628, "Suami", "Husband", R.drawable.img_bim_suami, "https://youtu.be/Y9o10N1RLfE", "", ""));
        list.add(new BimSignItem(1268, "Sampan", "Sampan", R.drawable.img_bim_sampan, "https://youtu.be/xRncWQdSmE4", "", ""));
        list.add(new BimSignItem(430, "Minggu depan", "Next week", R.drawable.img_bim_minggu_depan, "https://youtu.be/hR6BS6cXRrk", "", ""));
        list.add(new BimSignItem(434, "Minggu lalu, Minggu lepas", "Last week", R.drawable.img_bim_minggu_lalu_minggu_lepas, "https://youtu.be/1GicEj3PNOg", "", ""));
        list.add(new BimSignItem(438, "Musim", "Season", R.drawable.img_bim_musim, "https://youtu.be/NQT2sdNAA8E", "", ""));
        list.add(new BimSignItem(442, "Petang", "Afternoon", R.drawable.img_bim_petang, "https://youtu.be/5WfOkCC63DI", "", ""));
        list.add(new BimSignItem(446, "Sekarang", "Now", R.drawable.img_bim_sekarang, "https://youtu.be/yqTOgSpQpQI", "", ""));
        list.add(new BimSignItem(450, "Tahun", "Year", R.drawable.img_bim_tahun, "https://youtu.be/SvEfWlEBcJk", "", ""));
        list.add(new BimSignItem(454, "Tahun ini", "This year", R.drawable.img_bim_tahun_ini, "https://youtu.be/6ci2z0w9pTg", "", ""));
        list.add(new BimSignItem(458, "Tahunan", "Annual", R.drawable.img_bim_tahunan, "https://youtu.be/3kqDboV6OIs", "", ""));
        list.add(new BimSignItem(462, "Waktu", "Time", R.drawable.img_bim_waktu, "https://youtu.be/3eGAKma3FbQ", "", ""));
        list.add(new BimSignItem(466, "Isnin", "Monday", R.drawable.img_bim_isnin, "https://youtu.be/deJWBEq6pgA", "", ""));
        list.add(new BimSignItem(470, "Khamis", "Thursday", R.drawable.img_bim_khamis, "https://youtu.be/mcsjiwkCOBA", "", ""));
        list.add(new BimSignItem(474, "Sabtu", "Saturday", R.drawable.img_bim_sabtu, "https://youtu.be/My8spplM4uw", "", ""));
        list.add(new BimSignItem(478, "Badan", "Body", R.drawable.img_bim_badan, "https://youtu.be/RcOJ0dSC9n8", "", ""));
        list.add(new BimSignItem(482, "Dada", "Chest", R.drawable.img_bim_dada, "https://youtu.be/5LK9VqurvRk", "", ""));
        list.add(new BimSignItem(486, "Dahi", "Forehead", R.drawable.img_bim_dahi, "https://youtu.be/6PayAjcmV3Y", "", ""));
        list.add(new BimSignItem(490, "Hidung", "Nose", R.drawable.img_bim_hidung, "https://youtu.be/Ortwp6itkpM", "", ""));
        list.add(new BimSignItem(494, "Kaki", "Leg", R.drawable.img_bim_kaki, "https://youtu.be/-_uKvDOkrP0", "", ""));
        list.add(new BimSignItem(498, "Kepala", "Head", R.drawable.img_bim_kepala, "https://youtu.be/peP3MQnmL0s", "", ""));
        list.add(new BimSignItem(502, "Lidah", "Tongue", R.drawable.img_bim_lidah, "https://youtu.be/VFBt9Ud2b2w", "", ""));
        list.add(new BimSignItem(506, "Muka, Wajah", "Face", R.drawable.img_bim_muka_wajah, "https://youtu.be/Ec5-FMYh5sU", "", ""));
        list.add(new BimSignItem(510, "Pipi", "Cheek", R.drawable.img_bim_pipi, "https://youtu.be/GwzWL_06vSM", "", ""));
        list.add(new BimSignItem(518, "Awak, Anda", "You", R.drawable.img_bim_awak_anda, "https://youtu.be/GSERjhVh82E", "", ""));
        list.add(new BimSignItem(522, "Datin (gelaran bagi isteri seseorang yg telah dianugerahi gelaran kehormatan Datuk (atau Dato’)", "Datin (title for the wife of a person who has been awarded the honorary title of Datuk (or Dato ’)", R.drawable.img_bim_datin_gelaran_bagi_isteri_seseorang_yg_telah_dianugerahi_gelaran_kehormatan_datuk_atau_dato, "https://youtu.be/6a5p7EnOBi8", "", ""));
        list.add(new BimSignItem(432, "Minggu ini", "This week", R.drawable.img_bim_minggu_ini, "https://youtu.be/32QBCYsxgMA", "", ""));
        list.add(new BimSignItem(436, "Minit", "Minute", R.drawable.img_bim_minit, "https://youtu.be/cW18QCb3eLs", "", ""));
        list.add(new BimSignItem(440, "Pagi", "Morning", R.drawable.img_bim_pagi, "https://youtu.be/1pZNska_QCs", "", ""));
        list.add(new BimSignItem(444, "Saat", "Second", R.drawable.img_bim_saat, "https://youtu.be/HTGTEeL2JUI", "", ""));
        list.add(new BimSignItem(448, "Semalam", "Yesterday", R.drawable.img_bim_semalam, "https://youtu.be/j2Abq9YHJio", "", ""));
        list.add(new BimSignItem(460, "Tengah Hari", "Noon", R.drawable.img_bim_tengah_hari, "https://youtu.be/oYXXTeVGSSw", "", ""));
        list.add(new BimSignItem(464, "Ahad", "Sunday", R.drawable.img_bim_ahad, "https://youtu.be/_RwhFJNYGr4", "", ""));
        list.add(new BimSignItem(468, "Jumaat", "Friday", R.drawable.img_bim_jumaat, "https://youtu.be/LQY7jFzY7vI", "", ""));
        list.add(new BimSignItem(472, "Rabu", "Wednesday", R.drawable.img_bim_rabu, "https://youtu.be/rycl7AXxBzE", "", ""));
        list.add(new BimSignItem(488, "Gigi", "Teeth", R.drawable.img_bim_gigi, "https://youtu.be/EwU8wcv-G0Y", "", ""));
        list.add(new BimSignItem(492, "Jari", "Fingers", R.drawable.img_bim_jari, "https://youtu.be/SowS91HYhP4", "", ""));
        list.add(new BimSignItem(496, "Kening", "Eyebrow", R.drawable.img_bim_kening, "https://youtu.be/OO1aml2MzCw", "", ""));
        list.add(new BimSignItem(512, "Rambut", "Hair", R.drawable.img_bim_rambut, "https://youtu.be/WGY9l69JlPE", "", ""));
        list.add(new BimSignItem(516, "Telinga", "Ear", R.drawable.img_bim_telinga, "https://youtu.be/HPiThQwNsbo", "", ""));
        list.add(new BimSignItem(540, "Puan", "Madam", R.drawable.img_bim_puan, "https://youtu.be/CSixGMgqnAo", "", ""));
        list.add(new BimSignItem(552, "Sendiri", "Self", R.drawable.img_bim_sendiri, "https://youtu.be/xvyNghsaFYY", "", ""));
        list.add(new BimSignItem(556, "Abang", "Elder brother", R.drawable.img_bim_abang, "https://youtu.be/LoGOEPehHa4", "", ""));
        list.add(new BimSignItem(564, "Anak", "Child", R.drawable.img_bim_anak, "https://youtu.be/ZSyNrJtQBqM", "", ""));
        list.add(new BimSignItem(584, "Cerai", "Divorce", R.drawable.img_bim_cerai, "https://youtu.be/_tGrIC2mVJk", "", ""));
        list.add(new BimSignItem(588, "Datuk", "Grandfather", R.drawable.img_bim_datuk, "https://youtu.be/NNrkBrEc0eA", "", ""));
        list.add(new BimSignItem(592, "Emak saudara", "Auntie", R.drawable.img_bim_emak_saudara, "https://youtu.be/yXkRTjy9P0Q", "", ""));
        list.add(new BimSignItem(596, "Isteri, Bini", "Wife", R.drawable.img_bim_isteri_bini, "https://youtu.be/wUDt56kSga8", "", ""));
        list.add(new BimSignItem(600, "Kakak", "Elder sister", R.drawable.img_bim_kakak, "https://youtu.be/U4Mf_p9DM0E", "", ""));
        list.add(new BimSignItem(526, "Dia", "He, She", R.drawable.img_bim_dia, "https://youtu.be/icGZ5LpZkcQ", "", ""));
        list.add(new BimSignItem(530, "Kami", "We", R.drawable.img_bim_kami, "https://youtu.be/b6i2u9KlBIc", "", ""));
        list.add(new BimSignItem(534, "Kita", "us", R.drawable.img_bim_kita, "https://youtu.be/1XyY_j6R3qg", "", ""));
        list.add(new BimSignItem(538, "Nama", "Name", R.drawable.img_bim_nama, "https://youtu.be/0SPq5YPBvjI", "", ""));
        list.add(new BimSignItem(542, "Putera", "Prince", R.drawable.img_bim_putera, "https://youtu.be/lpIRVJ0DkWU", "", ""));
        list.add(new BimSignItem(546, "Saudara (kata ganti diri kedua yang digunakan pada lelaki)", "Mister (the second pronoun used in males)", R.drawable.img_bim_saudara_kata_ganti_diri_kedua_yang_digunakan_pada_lelaki, "https://youtu.be/mFIWfYirKNM", "", ""));
        list.add(new BimSignItem(550, "Saya", "I, Me", R.drawable.img_bim_saya, "https://youtu.be/hFlubKThPdE", "", ""));
        list.add(new BimSignItem(554, "Tuan", "Sir", R.drawable.img_bim_tuan, "https://youtu.be/0s4hwUGmIDM", "", ""));
        list.add(new BimSignItem(558, "Adik lelaki", "Younger brother", R.drawable.img_bim_adik_lelaki, "https://youtu.be/jA1p1ZZaIUo", "", ""));
        list.add(new BimSignItem(562, "Akad nikah", "Marriage vow", R.drawable.img_bim_akad_nikah, "https://youtu.be/lEUi52ZKnRM", "", ""));
        list.add(new BimSignItem(566, "Anak lelaki", "Son", R.drawable.img_bim_anak_lelaki, "https://youtu.be/hXLt3rXbcsE", "", ""));
        list.add(new BimSignItem(1678, "Karut", "Nonsense", R.drawable.img_bim_karut, "https://youtu.be/8dfwgNF_xG8", "", ""));
        list.add(new BimSignItem(3080, "Berhenti", "Stop (I)", R.drawable.img_bim_berhenti, "https://youtu.be/pDG9bf5vFhA", "", ""));
        list.add(new BimSignItem(3086, "Campur", "Mix", R.drawable.img_bim_campur, "https://youtu.be/PZPU7Tr9csM", "", ""));
        list.add(new BimSignItem(3096, "Iring", "Accompany", R.drawable.img_bim_iring, "https://youtu.be/fPdiN_lxV7g", "", ""));
        list.add(new BimSignItem(3100, "Keluar", "Exit", R.drawable.img_bim_keluar, "https://youtu.be/k6-_3jkUPAE", "", ""));
        list.add(new BimSignItem(3104, "Lepak", "Loiter", R.drawable.img_bim_lepak, "https://youtu.be/Zy1e4qH69cM", "", ""));
        list.add(new BimSignItem(3108, "Masuk", "Enter", R.drawable.img_bim_masuk, "https://youtu.be/H7wz7JbpQs0", "", ""));
        list.add(new BimSignItem(3078, "Anjur", "Organize", R.drawable.img_bim_anjur, "https://youtu.be/Zt65DkyqfTA", "", ""));
        list.add(new BimSignItem(3082, "Berlaku", "Happen", R.drawable.img_bim_berlaku, "https://youtu.be/tNuL5f0ww7E", "", ""));
        list.add(new BimSignItem(3090, "Datang (I)", "Come (I)", R.drawable.img_bim_datang_i, "https://youtu.be/TRBgXy3W8Kg", "", ""));
        list.add(new BimSignItem(3094, "Gilir", "Take in turns", R.drawable.img_bim_gilir, "https://youtu.be/-zjL8HGMpNQ", "", ""));
        list.add(new BimSignItem(3098, "Jadi", "Become", R.drawable.img_bim_jadi, "https://youtu.be/g8Y2BQW9_4c", "", ""));
        list.add(new BimSignItem(3102, "Kembali, Balik", "Return", R.drawable.img_bim_kembali_balik, "https://youtu.be/vtON2x3psDk", "", ""));
        list.add(new BimSignItem(3106, "Letup", "Explode", R.drawable.img_bim_letup, "https://youtu.be/MRS-D33s7fg", "", ""));
        list.add(new BimSignItem(3110, "Mati, Meninggal dunia", "Dead, pass away", R.drawable.img_bim_mati_meninggal_dunia, "https://youtu.be/s9Y6IiRLKj0", "", ""));
        list.add(new BimSignItem(3118, "Muncul", "Appear", R.drawable.img_bim_muncul, "https://youtu.be/osOV00HbBVY", "", ""));
        list.add(new BimSignItem(3122, "Pergi (I)", "Go (I)", R.drawable.img_bim_pergi_i, "https://youtu.be/Bf4I_20gTZE", "", ""));
        list.add(new BimSignItem(3126, "Pesong", "To change direction", R.drawable.img_bim_pesong, "https://youtu.be/bYqiZMe8xqE", "", ""));
        list.add(new BimSignItem(3132, "Putus (II)", "Disconnect (II)", R.drawable.img_bim_putus_ii, "https://youtu.be/Aj0hsvQ9jgY", "", ""));
        list.add(new BimSignItem(3136, "Sambung", "Continue (II)", R.drawable.img_bim_sambung, "https://youtu.be/ojdgFmKygbo", "", ""));
        list.add(new BimSignItem(3142, "Surai", "Dissolve", R.drawable.img_bim_surai, "https://youtu.be/xcvQchyvoEY", "", ""));
        list.add(new BimSignItem(3084, "Bersiar-siar", "Take a walk", R.drawable.img_bim_bersiar_siar, "https://youtu.be/BSkZxKj9Qck", "", ""));
        list.add(new BimSignItem(3088, "Cegah", "Protect", R.drawable.img_bim_cegah, "https://youtu.be/QzTBQKyz6QU", "", ""));
        list.add(new BimSignItem(3092, "Datang (II)", "Come (II)", R.drawable.img_bim_datang_ii, "https://youtu.be/pu7CrpTVZec", "", ""));
        list.add(new BimSignItem(3112, "Membeli-belah", "Shopping", R.drawable.img_bim_membeli_belah, "https://youtu.be/dqykWgB41GE", "", ""));
        list.add(new BimSignItem(3116, "Merosot", "Degenerate", R.drawable.img_bim_merosot, "https://youtu.be/kcI2VO8QDPw", "", ""));
        list.add(new BimSignItem(3130, "Putus (I)", "Disconnect (I)", R.drawable.img_bim_putus_i, "https://youtu.be/nqCaoIxtfPQ", "", ""));
        list.add(new BimSignItem(3134, "Runtuh", "Collapse", R.drawable.img_bim_runtuh, "https://youtu.be/Ko8KYGh7CWQ", "", ""));
        list.add(new BimSignItem(3140, "Sembunyi (II)", "Hide (II)", R.drawable.img_bim_sembunyi_ii, "https://youtu.be/TT1_gmxMKrM", "", ""));
        list.add(new BimSignItem(3114, "Merdeka", "Independent (III)", R.drawable.img_bim_merdeka, "https://youtu.be/-aPEKb7E3Ew", "", ""));
        list.add(new BimSignItem(3120, "Pengaruh", "Influence", R.drawable.img_bim_pengaruh, "https://youtu.be/msxtBiJv8c4", "", ""));
        list.add(new BimSignItem(3124, "Pergi (II)", "Go (II)", R.drawable.img_bim_pergi_ii, "https://youtu.be/iHnRQjR-on0", "", ""));
        list.add(new BimSignItem(3128, "Pisah", "Separate (II)", R.drawable.img_bim_pisah, "https://youtu.be/oGYgfOyW87Y", "", ""));
        list.add(new BimSignItem(3138, "Sampai", "Arrive", R.drawable.img_bim_sampai, "https://youtu.be/1xlKnrObDgI", "", ""));
        list.add(new BimSignItem(3144, "Taja", "Sponsor", R.drawable.img_bim_taja, "https://youtu.be/x7yRDLjC3dk", "", ""));
        list.add(new BimSignItem(3146, "Ulang", "Repeat", R.drawable.img_bim_ulang, "https://youtu.be/BR0wvShdV2E", "", ""));
        list.add(new BimSignItem(3148, "Ulang-alik", "Commute", R.drawable.img_bim_ulang_alik, "https://youtu.be/yY_xMRKvyP4", "", ""));
        list.add(new BimSignItem(3266, "Tahan (menahan, menghentikan)", "Stop (II)", R.drawable.img_bim_tahan_menahan_menghentikan, "https://youtu.be/zmNL3WgP_A0", "", ""));
        list.add(new BimSignItem(3272, "Tarik (tertarik)", "Fascinated", R.drawable.img_bim_tarik_tertarik, "https://youtu.be/43uP9RBkv_Q", "", ""));
        list.add(new BimSignItem(3276, "Tikam (menikam)", "Stab", R.drawable.img_bim_tikam_menikam, "https://youtu.be/_Cu6QRJQYzc", "", ""));
        list.add(new BimSignItem(3280, "Tunda (II)", "Adjourn", R.drawable.img_bim_tunda_ii, "https://youtu.be/E9W0CcyMXEQ", "", ""));
        list.add(new BimSignItem(3282, "Angin (masuk angin)", "Upset stomach, bloating", R.drawable.img_bim_angin_masuk_angin, "https://youtu.be/Z6DWpEh7EHY", "", ""));
        list.add(new BimSignItem(3286, "Gila, Edan", "Crazy", R.drawable.img_bim_gila_edan, "https://youtu.be/S-yZQ6tRK9A", "", ""));
        list.add(new BimSignItem(3288, "Hamil, Mengandung", "Pregnant", R.drawable.img_bim_hamil_mengandung, "https://youtu.be/WbFwld86If8", "", ""));
        list.add(new BimSignItem(3290, "Jangkitan", "Infection", R.drawable.img_bim_jangkitan, "https://youtu.be/v51KL2x2B28", "", ""));
        list.add(new BimSignItem(3294, "Kondom", "Condom", R.drawable.img_bim_kondom, "https://youtu.be/eGHKIwn2_7w", "", ""));
        list.add(new BimSignItem(3296, "Lemak", "Fat (fatty)", R.drawable.img_bim_lemak, "https://youtu.be/e7mjmK2lQyc", "", ""));
        list.add(new BimSignItem(3300, "Sakit, Penyakit", "Sick, Disease", R.drawable.img_bim_sakit_penyakit, "https://youtu.be/Bt95tREA6cw", "", ""));
        list.add(new BimSignItem(3304, "Pil", "Pill", R.drawable.img_bim_pil, "https://youtu.be/SwHs8_JNLjU", "", ""));
        list.add(new BimSignItem(3326, "Debu", "Dust", R.drawable.img_bim_debu, "https://youtu.be/dlfuU-4qfWk", "", ""));
        list.add(new BimSignItem(3330, "Emas", "Gold", R.drawable.img_bim_emas, "https://youtu.be/P-rXj5mjZvQ", "", ""));
        list.add(new BimSignItem(3342, "Alamat", "Address", R.drawable.img_bim_alamat, "https://youtu.be/qBUwc9gjtZQ", "", ""));
        list.add(new BimSignItem(3348, "Disko", "Disco", R.drawable.img_bim_disko, "https://youtu.be/lI8TLxWgtMg", "", ""));
        list.add(new BimSignItem(3356, "Kafeteria", "Cafeteria", R.drawable.img_bim_kafeteria, "https://youtu.be/8M6IHcwyLIM", "", ""));
        list.add(new BimSignItem(3364, "Lembah", "Valley", R.drawable.img_bim_lembah, "https://youtu.be/qd1Lms35Mpo", "", ""));
        list.add(new BimSignItem(3374, "Peta", "Map", R.drawable.img_bim_peta, "https://youtu.be/ZK37sEpDCWs", "", ""));
        list.add(new BimSignItem(3380, "Yayasan", "Foundation", R.drawable.img_bim_yayasan, "https://youtu.be/wxN9lgMvFdA", "", ""));
        list.add(new BimSignItem(3388, "Hari jadi (I)", "Birthday (I)", R.drawable.img_bim_hari_jadi_i, "https://youtu.be/cMooMOComDE", "", ""));
        list.add(new BimSignItem(3394, "Kempen", "Campaign", R.drawable.img_bim_kempen, "https://youtu.be/VUEDvmo6NYE", "", ""));
        list.add(new BimSignItem(3398, "Majlis (I)", "Ceremony", R.drawable.img_bim_majlis_i, "https://youtu.be/uKtj8_ailV8", "", ""));
        list.add(new BimSignItem(3402, "Motivasi", "Motivation", R.drawable.img_bim_motivasi, "https://youtu.be/YnimJ_kojt0", "", ""));
        list.add(new BimSignItem(3406, "Pameran", "Exhibition", R.drawable.img_bim_pameran, "https://youtu.be/WiFxeFjDJhc", "", ""));
        list.add(new BimSignItem(3410, "Perarakan", "Parade", R.drawable.img_bim_perarakan, "https://youtu.be/tqonNrCLjXg", "", ""));
        list.add(new BimSignItem(3414, "Perhimpunan", "Assembly", R.drawable.img_bim_perhimpunan, "https://youtu.be/FHhQ_rAqbQw", "", ""));
        list.add(new BimSignItem(3418, "Pertunjukan", "Show (II)", R.drawable.img_bim_pertunjukan, "https://youtu.be/P3h9lxTC1a0", "", ""));
        list.add(new BimSignItem(3328, "Elastik", "Elastic", R.drawable.img_bim_elastik, "https://youtu.be/CgWFppp58kk", "", ""));
        list.add(new BimSignItem(3340, "Timah", "Tin", R.drawable.img_bim_timah, "https://youtu.be/Yvng54JJlQI", "", ""));
        list.add(new BimSignItem(3346, "Dewan", "Hall", R.drawable.img_bim_dewan, "https://youtu.be/z1h238tlBxA", "", ""));
        list.add(new BimSignItem(3354, "Gurun", "Desert", R.drawable.img_bim_gurun, "https://youtu.be/nJk_L_9MDc4", "", ""));
        list.add(new BimSignItem(3360, "Kedutaan", "Embassy", R.drawable.img_bim_kedutaan, "https://youtu.be/-arWT_LP3aQ", "", ""));
        list.add(new BimSignItem(3366, "Lif", "Elevator", R.drawable.img_bim_lif, "https://youtu.be/x4UjF09xDsw", "", ""));
        list.add(new BimSignItem(3370, "Padang", "Field", R.drawable.img_bim_padang, "https://youtu.be/Rf9LEHb0iAs", "", ""));
        list.add(new BimSignItem(3378, "Tempat", "Place", R.drawable.img_bim_tempat, "https://youtu.be/xBA9rG-JGqc", "", ""));
        list.add(new BimSignItem(3384, "Ceramah", "Lecture", R.drawable.img_bim_ceramah, "https://youtu.be/EgVd9Z10lMs", "", ""));
        list.add(new BimSignItem(3390, "Hari jadi (II)", "Birthday (II)", R.drawable.img_bim_hari_jadi_ii, "https://youtu.be/gSXtRdocoF0", "", ""));
        list.add(new BimSignItem(3404, "Orientasi", "Orientation", R.drawable.img_bim_orientasi, "https://youtu.be/aojZc1blPs4", "", ""));
        list.add(new BimSignItem(3412, "Perasmian", "Launching", R.drawable.img_bim_perasmian, "https://youtu.be/h0K1aostqvM", "", ""));
        list.add(new BimSignItem(3416, "Perlawanan", "Match", R.drawable.img_bim_perlawanan, "https://youtu.be/XdjrxgDI7Ro", "", ""));
        list.add(new BimSignItem(3512, "Bomoh (Cina)", "Traditional Healer (Chinese)", R.drawable.img_bim_bomoh_cina, "https://youtu.be/tOaOuGY39tA", "", ""));
        list.add(new BimSignItem(3518, "Duta", "Ambassador", R.drawable.img_bim_duta, "https://youtu.be/0LkZYG52B58", "", ""));
        list.add(new BimSignItem(3522, "Kapten (Pihak Berkuasa)", "Captain (Authority)", R.drawable.img_bim_kapten_pihak_berkuasa, "https://youtu.be/44yhCqEcA8Y", "", ""));
        list.add(new BimSignItem(3332, "Gangsa", "Bronze", R.drawable.img_bim_gangsa, "https://youtu.be/SO_lRKiHHlw", "", ""));
        list.add(new BimSignItem(3336, "Pasir", "Sand", R.drawable.img_bim_pasir, "https://youtu.be/Aff1x4dSVLs", "", ""));
        list.add(new BimSignItem(3344, "Cawangan", "Branch", R.drawable.img_bim_cawangan, "https://youtu.be/ULiZruShRQw", "", ""));
        list.add(new BimSignItem(3350, "Dobi", "Laundry", R.drawable.img_bim_dobi, "https://youtu.be/TJwxREzMb_E", "", ""));
        list.add(new BimSignItem(3358, "Kaunter", "Counter", R.drawable.img_bim_kaunter, "https://youtu.be/OI1fu-DLCiM", "", ""));
        list.add(new BimSignItem(3362, "Kondominium", "Condominium", R.drawable.img_bim_kondominium, "https://youtu.be/1KWe09obh2s", "", ""));
        list.add(new BimSignItem(3368, "Lubang", "Hole", R.drawable.img_bim_lubang, "https://youtu.be/gEbDdcKI1fI", "", ""));
        list.add(new BimSignItem(3372, "Penjara", "Prison", R.drawable.img_bim_penjara, "https://youtu.be/YhlgXXLIF2w", "", ""));
        list.add(new BimSignItem(3376, "Taman", "Garden", R.drawable.img_bim_taman, "https://youtu.be/-7-wqNbDGNU", "", ""));
        list.add(new BimSignItem(3382, "Cenderamata", "Souvenir", R.drawable.img_bim_cenderamata, "https://youtu.be/_dOYhGIp2_o", "", ""));
        list.add(new BimSignItem(3386, "Hadiah", "Gift", R.drawable.img_bim_hadiah, "https://youtu.be/Ji35oJkSb0o", "", ""));
        list.add(new BimSignItem(3392, "Khemah", "Tent", R.drawable.img_bim_khemah, "https://youtu.be/nZKM9MP8Z40", "", ""));
        list.add(new BimSignItem(3396, "Kenduri", "Feast", R.drawable.img_bim_kenduri, "https://youtu.be/iHpa64NcS9E", "", ""));
        list.add(new BimSignItem(3400, "Majlis (II)", "Council", R.drawable.img_bim_majlis_ii, "https://youtu.be/Vi-JUeI456Q", "", ""));
        list.add(new BimSignItem(3408, "Parti", "Party", R.drawable.img_bim_parti, "https://youtu.be/jwYqndqiAXg", "", ""));
        list.add(new BimSignItem(3420, "Ulang tahun", "Anniversary", R.drawable.img_bim_ulang_tahun, "https://youtu.be/QSo741QZaSc", "", ""));
        list.add(new BimSignItem(3508, "Anak bongsu", "Last child", R.drawable.img_bim_anak_bongsu, "https://youtu.be/8GYpNo9qdv0", "", ""));
        list.add(new BimSignItem(3516, "Bulu", "Fur", R.drawable.img_bim_bulu, "https://youtu.be/stUYghoSVFA", "", ""));
        list.add(new BimSignItem(3520, "Junior", "Junior", R.drawable.img_bim_junior, "https://youtu.be/OLTN8la-Iwg", "", ""));
        list.add(new BimSignItem(3524, "Kapten (Sukan)", "Captain (Sports)", R.drawable.img_bim_kapten_sukan, "https://youtu.be/_SzkR2i0HGQ", "", ""));
        list.add(new BimSignItem(3532, "Lanun", "Pirate", R.drawable.img_bim_lanun, "https://youtu.be/SI9WowKbJZI", "", ""));
        list.add(new BimSignItem(3538, "Musuh", "Enemy", R.drawable.img_bim_musuh, "https://youtu.be/iv73uf7_DbI", "", ""));
        list.add(new BimSignItem(3542, "Pakar", "Expert, Specialist", R.drawable.img_bim_pakar, "https://youtu.be/88HSb61JP_g", "", ""));
        list.add(new BimSignItem(3550, "Pemimpin", "Leader, Guide", R.drawable.img_bim_pemimpin, "https://youtu.be/GAcHvaZ3lXE", "", ""));
        list.add(new BimSignItem(3554, "Pengaturcara", "Programmer", R.drawable.img_bim_pengaturcara, "https://youtu.be/Of2bauASfl4", "", ""));
        list.add(new BimSignItem(3510, "Anak sulung", "First-born", R.drawable.img_bim_anak_sulung, "https://youtu.be/Md5ZEB6M8Qw", "", ""));
        list.add(new BimSignItem(3514, "Bomoh (Melayu)", "Traditional Healer (Malay)", R.drawable.img_bim_bomoh_melayu, "https://youtu.be/pdam8OssaoE", "", ""));
        list.add(new BimSignItem(3528, "Ketua (II)", "Chief, Supervisor", R.drawable.img_bim_ketua_ii, "https://youtu.be/fILU1CmlirE", "", ""));
        list.add(new BimSignItem(3536, "Mekanik", "Mechanic", R.drawable.img_bim_mekanik, "https://youtu.be/IuVX32ChlfU", "", ""));
        list.add(new BimSignItem(3540, "Orang asli", "Indigenous people", R.drawable.img_bim_orang_asli, "https://youtu.be/nya3MtoHkqw", "", ""));
        list.add(new BimSignItem(3544, "Pelancong", "Tourist", R.drawable.img_bim_pelancong, "https://youtu.be/Gx_pB2EzhCo", "", ""));
        list.add(new BimSignItem(3548, "Pemerhati (Pemantau)", "Observer (Monitor)", R.drawable.img_bim_pemerhati_pemantau, "https://youtu.be/IE67o5DbCEs", "", ""));
        list.add(new BimSignItem(3552, "Pencuri", "Thief", R.drawable.img_bim_pencuri, "https://youtu.be/vgJS2LoQD0U", "", ""));
        list.add(new BimSignItem(3556, "Pengembara (Beg galas)", "Backpacker", R.drawable.img_bim_pengembara_beg_galas, "https://youtu.be/3fZJCZVxChA", "", ""));
        list.add(new BimSignItem(3534, "Mamak", "Mamak", R.drawable.img_bim_mamak, "https://youtu.be/8MJERfpYE18", "", ""));
        list.add(new BimSignItem(3558, "Pengembara tumpang", "Hitch-hiker", R.drawable.img_bim_pengembara_tumpang, "https://youtu.be/WkwRy4ChoAA", "", ""));
        list.add(new BimSignItem(3560, "Pengemis", "Beggar", R.drawable.img_bim_pengemis, "https://youtu.be/sfJwhiI89FI", "", ""));
        list.add(new BimSignItem(3562, "Pengerusi", "Chairperson", R.drawable.img_bim_pengerusi, "https://youtu.be/G3570JaOaBg", "", ""));
        list.add(new BimSignItem(3564, "Pengintip (I)", "Spy (I)", R.drawable.img_bim_pengintip_i, "https://youtu.be/vgCtGRiblQE", "", ""));
        list.add(new BimSignItem(4154, "Amat jelas", "Very clear", R.drawable.img_bim_amat_jelas, "https://youtu.be/GaCKQfy2Oio", "", ""));
        list.add(new BimSignItem(4160, "Asyik rindu", "Absorbed, keep thinking about something or someone", R.drawable.img_bim_asyik_rindu, "https://youtu.be/dSRMvVUlc90", "", ""));
        list.add(new BimSignItem(4166, "Beli dulu, bayar kemudian", "Buy first, pay later", R.drawable.img_bim_beli_dulu_bayar_kemudian, "https://youtu.be/fHyJRyjZ02Q", "", ""));
        list.add(new BimSignItem(4172, "Berlengah-lengah", "Keep delaying", R.drawable.img_bim_berlengah_lengah, "https://youtu.be/lwQfKN4DgJA", "", ""));
        list.add(new BimSignItem(4176, "Betapa rumitnya!", "How complicated!", R.drawable.img_bim_betapa_rumitnya, "https://youtu.be/ndcxReHXr8M", "", ""));
        list.add(new BimSignItem(4180, "Buat terlebih dulu", "Let me do it first", R.drawable.img_bim_buat_terlebih_dulu, "https://youtu.be/H_Togr4DfwQ", "", ""));
        list.add(new BimSignItem(4190, "Di luar pengetahuan", "Beyond knowledge", R.drawable.img_bim_di_luar_pengetahuan, "https://youtu.be/MaWgu7xjTIM", "", ""));
        list.add(new BimSignItem(4194, "Bijak!", "Genius!", R.drawable.img_bim_bijak, "https://youtu.be/5AKToEtlXmE", "", ""));
        list.add(new BimSignItem(4198, "Habislah saya!", "I am damned!", R.drawable.img_bim_habislah_saya, "https://youtu.be/MO8I_SWoHqU", "", ""));
        list.add(new BimSignItem(4204, "Ingin tahu", "Curious", R.drawable.img_bim_ingin_tahu, "https://youtu.be/79j2swmREPI", "", ""));
        list.add(new BimSignItem(4208, "Jatuh nama", "To get a bad name", R.drawable.img_bim_jatuh_nama, "https://youtu.be/_IfKRdsVWM8", "", ""));
        list.add(new BimSignItem(4214, "Kulit menjadi perang", "Cause to tan", R.drawable.img_bim_kulit_menjadi_perang, "https://youtu.be/sXyg_MOe0LQ", "", ""));
        list.add(new BimSignItem(4218, "Laju (bahasa isyarat)", "Too fast (sign language)", R.drawable.img_bim_laju_bahasa_isyarat, "https://youtu.be/C4FmMR_MADI", "", ""));
        list.add(new BimSignItem(4222, "Lepas tangan", "Don't involve oneself", R.drawable.img_bim_lepas_tangan, "https://youtu.be/1aZeZNZNsg0", "", ""));
        list.add(new BimSignItem(4228, "Main-main saja", "Just kidding", R.drawable.img_bim_main_main_saja, "https://youtu.be/16JMo_z0kds", "", ""));
        list.add(new BimSignItem(4232, "Mata terbeliak", "Wide-open eyes", R.drawable.img_bim_mata_terbeliak, "https://youtu.be/Iz4U8yeMX9Q", "", ""));
        list.add(new BimSignItem(4156, "Amboi kaya", "How wealthy!", R.drawable.img_bim_amboi_kaya, "https://youtu.be/aGUKqY0lET8", "", ""));
        list.add(new BimSignItem(4162, "Bagaimana awak tahu?", "How do you know?", R.drawable.img_bim_bagaimana_awak_tahu, "https://youtu.be/sEPD1WBsPws", "", ""));
        list.add(new BimSignItem(4168, "Beres!", "Done!", R.drawable.img_bim_beres, "https://youtu.be/ODpSGbi4kw8", "", ""));
        list.add(new BimSignItem(4178, "Buat apa?", "Do what?", R.drawable.img_bim_buat_apa, "https://youtu.be/wFDSCyyxFfg", "", ""));
        list.add(new BimSignItem(4184, "Cabut lari", "Run away", R.drawable.img_bim_cabut_lari, "https://youtu.be/YLcBaJSB1rQ", "", ""));
        list.add(new BimSignItem(4188, "Dari pagi hingga malam", "From morning till night", R.drawable.img_bim_dari_pagi_hingga_malam, "https://youtu.be/8h2XfZhaNbw", "", ""));
        list.add(new BimSignItem(4202, "Ingin melihat / tahu", "Curious to see / know", R.drawable.img_bim_ingin_melihat_tahu, "https://youtu.be/jgH-KOrwPxo", "", ""));
        list.add(new BimSignItem(4206, "Janji kosong", "Empty promise", R.drawable.img_bim_janji_kosong, "https://youtu.be/iupyQSLEmMY", "", ""));
        list.add(new BimSignItem(4220, "Lebih baik daripada", "Better than", R.drawable.img_bim_lebih_baik_daripada, "https://youtu.be/1sJi_iEUzwI", "", ""));
        list.add(new BimSignItem(4226, "Mahal, Sangat mahal", "Expensive, Exorbitant", R.drawable.img_bim_mahal_sangat_mahal, "https://youtu.be/_8Pl9333nK4", "", ""));
        list.add(new BimSignItem(4240, "Membuta tuli", "Reckless", R.drawable.img_bim_membuta_tuli, "https://youtu.be/MtUzHaPv5sc", "", ""));
        list.add(new BimSignItem(4252, "Mengambil kesempatan", "Take advantage of", R.drawable.img_bim_mengambil_kesempatan, "https://youtu.be/qfJZS2aGvpA", "", ""));
        list.add(new BimSignItem(4258, "Muak", "Sick of", R.drawable.img_bim_muak, "https://youtu.be/TBSXX6aYn2k", "", ""));
        list.add(new BimSignItem(4262, "Nampak?", "Did you see?", R.drawable.img_bim_nampak, "https://youtu.be/_kPPxPz9k6o", "", ""));
        list.add(new BimSignItem(4268, "Oh! Begitu rupanya", "Oh! I see", R.drawable.img_bim_oh_begitu_rupanya, "https://youtu.be/B4QLneQyO6o", "", ""));
        list.add(new BimSignItem(4278, "Putus hubungan", "Break off", R.drawable.img_bim_putus_hubungan, "https://youtu.be/bfaF3FuBj3c", "", ""));
        list.add(new BimSignItem(4282, "Rugi masa", "Waste of time", R.drawable.img_bim_rugi_masa, "https://youtu.be/kbXE5OKBnus", "", ""));
        list.add(new BimSignItem(4286, "Sambil lewa", "Half-heartedly", R.drawable.img_bim_sambil_lewa, "https://youtu.be/iFbp58siZzA", "", ""));
        list.add(new BimSignItem(4292, "Semakin bertambah", "Increased", R.drawable.img_bim_semakin_bertambah, "https://youtu.be/LGuetBim3ac", "", ""));
        list.add(new BimSignItem(4296, "Semua pandang saya", "Everyone looking at me", R.drawable.img_bim_semua_pandang_saya, "https://youtu.be/wxUBrayKJw8", "", ""));
        list.add(new BimSignItem(4158, "Apa gunanya", "What for", R.drawable.img_bim_apa_gunanya, "https://youtu.be/1jVd_me1il4", "", ""));
        list.add(new BimSignItem(4164, "Balik ke rumah", "Going home", R.drawable.img_bim_balik_ke_rumah, "https://youtu.be/e2qZDr-DRkY", "", ""));
        list.add(new BimSignItem(4170, "Bergoyang kaki", "Live easily, loaf around", R.drawable.img_bim_bergoyang_kaki, "https://youtu.be/vjoMsLNkgbA", "", ""));
        list.add(new BimSignItem(4174, "Bernasib baik!", "Lucky!", R.drawable.img_bim_bernasib_baik, "https://youtu.be/HsKF1MYq9Wo", "", ""));
        list.add(new BimSignItem(4182, "Buka rahsia", "Reveal secrets", R.drawable.img_bim_buka_rahsia, "https://youtu.be/hrE8ep-ISM0", "", ""));
        list.add(new BimSignItem(4186, "Cepat (II)", "Hurry", R.drawable.img_bim_cepat_ii, "https://youtu.be/KyrvIEygCTQ", "", ""));
        list.add(new BimSignItem(4192, "Diperbodohkan", "Being fooled", R.drawable.img_bim_diperbodohkan, "https://youtu.be/3ya_OSXXXxo", "", ""));
        list.add(new BimSignItem(4196, "Habislah awak!", "You are damned!", R.drawable.img_bim_habislah_awak, "https://youtu.be/ghCmygFWLpY", "", ""));
        list.add(new BimSignItem(4200, "Imej terjejas", "Get a bad image", R.drawable.img_bim_imej_terjejas, "https://youtu.be/hL3LOWj1n1E", "", ""));
        list.add(new BimSignItem(4212, "Kesuntukan masa", "Not much time", R.drawable.img_bim_kesuntukan_masa, "https://youtu.be/ZJngaKQy7Rg", "", ""));
        list.add(new BimSignItem(4216, "Lain cerita", "Like to change topic", R.drawable.img_bim_lain_cerita, "https://youtu.be/fZpto0d1DS0", "", ""));
        list.add(new BimSignItem(4224, "Lupakan saja!", "Forget it!", R.drawable.img_bim_lupakan_saja, "https://youtu.be/Xtmjh9TFFI4", "", ""));
        list.add(new BimSignItem(4230, "Masuk telinga, keluar telinga", "Not Listening", R.drawable.img_bim_masuk_telinga_keluar_telinga, "https://youtu.be/pbDBWY-5tnI", "", ""));
        list.add(new BimSignItem(4234, "Membasuh otak", "Brainwash", R.drawable.img_bim_membasuh_otak, "https://youtu.be/AQJiU8Qn-YI", "", ""));
        list.add(new BimSignItem(4238, "Membiasakan diri", "Getting used to", R.drawable.img_bim_membiasakan_diri, "https://youtu.be/VOumaLDkbSQ", "", ""));
        list.add(new BimSignItem(4242, "Mempunyai banyak wang", "Have plenty of money", R.drawable.img_bim_mempunyai_banyak_wang, "https://youtu.be/zqi3zonPZLc", "", ""));
        list.add(new BimSignItem(4246, "Mencuci mata", "Enjoy watching something or someone beautiful", R.drawable.img_bim_mencuci_mata, "https://youtu.be/wJjLp4t-jnI", "", ""));
        list.add(new BimSignItem(4250, "Menebalkan muka", "Thick-skinned", R.drawable.img_bim_menebalkan_muka, "https://youtu.be/F_wcc4skOYw", "", ""));
        list.add(new BimSignItem(4254, "Menyakitkan mata", "Eyesore", R.drawable.img_bim_menyakitkan_mata, "https://youtu.be/w6HW9aM5DZU", "", ""));
        list.add(new BimSignItem(4266, "Nyah!", "Get away!", R.drawable.img_bim_nyah, "https://youtu.be/8JtplRvh1Yg", "", ""));
        list.add(new BimSignItem(4270, "Padan muka!", "Serve you right!", R.drawable.img_bim_padan_muka, "https://youtu.be/AJum1ZR8SFM", "", ""));
        list.add(new BimSignItem(4274, "Prestasi baik", "Good performance", R.drawable.img_bim_prestasi_baik, "https://youtu.be/u_fcGdykVeY", "", ""));
        list.add(new BimSignItem(4288, "Sangat mudah", "Very easy", R.drawable.img_bim_sangat_mudah, "https://youtu.be/AB7fhfMlnOQ", "", ""));
        list.add(new BimSignItem(4236, "Memberi muka", "Give face", R.drawable.img_bim_memberi_muka, "https://youtu.be/B7Z7JHh-HQI", "", ""));
        list.add(new BimSignItem(4244, "Mencari nama", "To make a name", R.drawable.img_bim_mencari_nama, "https://youtu.be/32dladF5ORE", "", ""));
        list.add(new BimSignItem(4248, "Mencuri tulang", "Steal time doing nothing", R.drawable.img_bim_mencuri_tulang, "https://youtu.be/FNCtuH1fDTQ", "", ""));
        list.add(new BimSignItem(4256, "Menyibuk", "Busybody", R.drawable.img_bim_menyibuk, "https://youtu.be/6OD93GbOKfQ", "", ""));
        list.add(new BimSignItem(4260, "Mudah saja", "It is easy", R.drawable.img_bim_mudah_saja, "https://youtu.be/x1egbtSG5Oc", "", ""));
        list.add(new BimSignItem(4264, "Nasib kamu baik!", "You are lucky!", R.drawable.img_bim_nasib_kamu_baik, "https://youtu.be/LFjyyXqRNo8", "", ""));
        list.add(new BimSignItem(4272, "Perkara kecil", "Small matter", R.drawable.img_bim_perkara_kecil, "https://youtu.be/Vww_busvw0g", "", ""));
        list.add(new BimSignItem(4276, "Prestasi buruk", "Bad performance", R.drawable.img_bim_prestasi_buruk, "https://youtu.be/VVoZtUG8PtA", "", ""));
        list.add(new BimSignItem(4280, "Rasa malas", "Feel lazy", R.drawable.img_bim_rasa_malas, "https://youtu.be/z1qM1YL671w", "", ""));
        list.add(new BimSignItem(4284, "Rugilah", "It's a loss!", R.drawable.img_bim_rugilah, "https://youtu.be/-DusbuNzdcs", "", ""));
        list.add(new BimSignItem(4290, "Sebagai balasan", "In return", R.drawable.img_bim_sebagai_balasan, "https://youtu.be/LsFvSy5021U", "", ""));
        list.add(new BimSignItem(4294, "Semakin menurun", "Decreased", R.drawable.img_bim_semakin_menurun, "https://youtu.be/bKbnGuUJDfE", "", ""));
        list.add(new BimSignItem(4302, "Siapa beritahu awak?", "Who told you?", R.drawable.img_bim_siapa_beritahu_awak, "https://youtu.be/Yc_9Aqqfd40", "", ""));
        list.add(new BimSignItem(4308, "Sudah bosan", "Bored already", R.drawable.img_bim_sudah_bosan, "https://youtu.be/q96zRj05hYU", "", ""));
        list.add(new BimSignItem(4312, "Sudah terlambat", "It's too late", R.drawable.img_bim_sudah_terlambat, "https://youtu.be/6-GIHM83Jg8", "", ""));
        list.add(new BimSignItem(4316, "Tarik perhatian", "Get attention", R.drawable.img_bim_tarik_perhatian, "https://youtu.be/FnhEjjs2APQ", "", ""));
        list.add(new BimSignItem(4320, "Terlepas cakap", "Accidentally said (Slip of the tongue)", R.drawable.img_bim_terlepas_cakap, "https://youtu.be/yr_2IEEWiKM", "", ""));
        list.add(new BimSignItem(4324, "Terpulang kepada (I)", "Up to (I)", R.drawable.img_bim_terpulang_kepada_i, "https://youtu.be/acQQMtKbhlE", "", ""));
        list.add(new BimSignItem(4328, "Tersilap", "Mistaken", R.drawable.img_bim_tersilap, "https://youtu.be/9xWu_K55mfQ", "", ""));
        list.add(new BimSignItem(4332, "Tiada ada kerja", "Nothing to do", R.drawable.img_bim_tiada_ada_kerja, "https://youtu.be/OAig5SY4f1E", "", ""));
        list.add(new BimSignItem(4336, "Tidak apa", "Never mind", R.drawable.img_bim_tidak_apa, "https://youtu.be/z1dKTagEv_E", "", ""));
        list.add(new BimSignItem(4340, "Tidak dapat ingat", "Can't remember", R.drawable.img_bim_tidak_dapat_ingat, "https://youtu.be/CNrlC3Bdtmg", "", ""));
        list.add(new BimSignItem(4350, "Tidak kisah", "Don't care", R.drawable.img_bim_tidak_kisah, "https://youtu.be/n_2rC3y9DOM", "", ""));
        list.add(new BimSignItem(4354, "Tidak mempunyai wang", "Have no money", R.drawable.img_bim_tidak_mempunyai_wang, "https://youtu.be/BLjdr2yGmQU", "", ""));
        list.add(new BimSignItem(4298, "Senang sahaja", "It's easy", R.drawable.img_bim_senang_sahaja, "https://youtu.be/Gv4WtzQtcJs", "", ""));
        list.add(new BimSignItem(4306, "Sudah biasa", "Used to it", R.drawable.img_bim_sudah_biasa, "https://youtu.be/9SGjsZnPfDk", "", ""));
        list.add(new BimSignItem(4322, "Terlepas peluang", "Missed opportunity", R.drawable.img_bim_terlepas_peluang, "https://youtu.be/QeUcc7yCoGE", "", ""));
        list.add(new BimSignItem(4334, "Tiada perasaan", "No feelings", R.drawable.img_bim_tiada_perasaan, "https://youtu.be/Mp2pdoynFUo", "", ""));
        list.add(new BimSignItem(4344, "Tidak dengar apa-apa", "Don't hear anything", R.drawable.img_bim_tidak_dengar_apa_apa, "https://youtu.be/UszlIVzMWVs", "", ""));
        list.add(new BimSignItem(4348, "Tidak kenal", "Do not know (person(s)", R.drawable.img_bim_tidak_kenal, "https://youtu.be/0c4_dX1qA5g", "", ""));
        list.add(new BimSignItem(4368, "Tidak sedap", "Not delicious", R.drawable.img_bim_tidak_sedap, "https://youtu.be/OqtbDgA4RcI", "", ""));
        list.add(new BimSignItem(4376, "Ulangi cerita sama", "Repeat the same story", R.drawable.img_bim_ulangi_cerita_sama, "https://youtu.be/dndeUvzPEj4", "", ""));
        list.add(new BimSignItem(4300, "Sia-sia sahaja", "In vain", R.drawable.img_bim_sia_sia_sahaja, "https://youtu.be/BBhDouztKFk", "", ""));
        list.add(new BimSignItem(4304, "Awak sudah berubah", "You have changed", R.drawable.img_bim_awak_sudah_berubah, "https://youtu.be/3Q2xnXxHpZ8", "", ""));
        list.add(new BimSignItem(4310, "Sudah lama", "Been a long time", R.drawable.img_bim_sudah_lama, "https://youtu.be/pzVCFsyLcMA", "", ""));
        list.add(new BimSignItem(4314, "Sukar difahami", "Difficult to understand", R.drawable.img_bim_sukar_difahami, "https://youtu.be/S9rutk-P5Zw", "", ""));
        list.add(new BimSignItem(4318, "Terlalu degil", "Very stubborn", R.drawable.img_bim_terlalu_degil, "https://youtu.be/29lloO0qIQg", "", ""));
        list.add(new BimSignItem(4326, "Terpulang kepada (II)", "Up to (II)", R.drawable.img_bim_terpulang_kepada_ii, "https://youtu.be/7mRIptxlXvk", "", ""));
        list.add(new BimSignItem(4330, "Teruk!", "Worse!", R.drawable.img_bim_teruk, "https://youtu.be/GBGXls_y-l8", "", ""));
        list.add(new BimSignItem(4338, "Tidak beri perhatian", "Don't pay attention", R.drawable.img_bim_tidak_beri_perhatian, "https://youtu.be/6JxT48VVe0w", "", ""));
        list.add(new BimSignItem(4342, "Tidak dapat melihat", "Can't see", R.drawable.img_bim_tidak_dapat_melihat, "https://youtu.be/zmw28y_STzQ", "", ""));
        list.add(new BimSignItem(4346, "Tidak elok", "Not nice", R.drawable.img_bim_tidak_elok, "https://youtu.be/drKilTXt2WA", "", ""));
        list.add(new BimSignItem(4352, "Tidak logik", "Don't make sense", R.drawable.img_bim_tidak_logik, "https://youtu.be/6stpEXLniCU", "", ""));
        list.add(new BimSignItem(4356, "Tidak menakutkan", "Not fearful", R.drawable.img_bim_tidak_menakutkan, "https://youtu.be/McUhGyN1W3s", "", ""));
        list.add(new BimSignItem(4360, "Tidak menumpukan", "Inattentive", R.drawable.img_bim_tidak_menumpukan, "https://youtu.be/JaFhJ16Va2I", "", ""));
        list.add(new BimSignItem(4364, "Tidak perlu buat", "Don't have to do", R.drawable.img_bim_tidak_perlu_buat, "https://youtu.be/M_h26YvXzsU", "", ""));
        list.add(new BimSignItem(4372, "Tidak tahan", "Can't stand it", R.drawable.img_bim_tidak_tahan, "https://youtu.be/SJ-p7Z8gQdE", "", ""));
        list.add(new BimSignItem(4358, "Tidak mengantuk", "Not sleepy", R.drawable.img_bim_tidak_mengantuk, "https://youtu.be/RX1qqv2bYS8", "", ""));
        list.add(new BimSignItem(4362, "Tidak pasti", "Unsure", R.drawable.img_bim_tidak_pasti, "https://youtu.be/_MBKRoOY_0Y", "", ""));
        list.add(new BimSignItem(4366, "Tidak rasa apa-apa", "Do not feel anything", R.drawable.img_bim_tidak_rasa_apa_apa, "https://youtu.be/q77_UAiaJRA", "", ""));
        list.add(new BimSignItem(4370, "Tidak suka berpanas", "Cannot stand the heat", R.drawable.img_bim_tidak_suka_berpanas, "https://youtu.be/YRZ707fYXCg", "", ""));
        list.add(new BimSignItem(4374, "Tidak tahu apa-apa", "Don't know anything", R.drawable.img_bim_tidak_tahu_apa_apa, "https://youtu.be/tNCSTPyYSmY", "", ""));
        cachedList = Collections.unmodifiableList(list);
        return cachedList;
    }
}
